# Generated by Django 2.0 on 2020-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', default=None, null=True)),
                ('organisation', models.CharField(blank=True, db_column='Organisation', max_length=50, null=True)),
                ('designation', models.CharField(blank=True, db_column='Designation', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('remark', models.TextField(blank=True, db_column='Remark', null=True)),
            ],
            options={
                'db_table': 'Survey_Data',
            },
        ),
    ]
